### ISSUE TITLE
Software stack for controls

### ISSUE THREAD

**Issue by jspspike** [ut-ras/robosub-sw#2]
- ROS?

**Comment by Reto0** [comment]
1. drivers for motors and sensors - no bitfiddling 

2. algorithms- ROS often used by researchers so alot of cutting edge algorithms available

3. infrastructure allows for split computers
The software is structured as a large number of small programs that rapidly pass messages to one another
move data around
distributed computation
multi threading

4. tools to visualize state of robot and algorithms ez debug
5. community- website to ask questions, wiki

saves time dont have to write software, focus on parts of the system

The Robot Operating System (ROS) is a framework for writing robot software.It is acollection of tools, libraries, and conventions 
This is used to simplify the task of creatingcomplex robot behavior across a wide variety of platforms.

ROS main source of information: http://wiki.ros.org/

Works best on linux

One way to visualize how an ROS system works is as several nodes. Each node can represent different things such as navigation, computer imaging, etc. These all run simultaneously and can communicate with each other.

This loosely coupled graph based architecture allows for easy prototyping with little software needed to make them all work together. Ex. Going back to the node visualization, a node representing computer imaging can be easily swapped with another simmilar one already written by someone else that accepts simmilar inputs and outputs.

**Comment by Reto0** [comment]
These nodes communicate using ROScore. All nodes during startup connect to ROScore this then links it with all other nodes it may input or output from.

ROS Packages
All software is organized into packages which contain some mix of code data and documentation. Python, C++, Lisp are natively supported and Java and Lua can be supported using experimental libraries
